CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    email VARCHAR2(100) UNIQUE,
    password VARCHAR2(100)
);

INSERT INTO users (name, email, password)
VALUES ('John Doe', 'john.doe@example.com', 'password123');

INSERT INTO users (name, email, password)
VALUES ('Jane Smith', 'jane.smith@example.com', 'securepass456');

INSERT INTO users (name, email, password)
VALUES ('Kwame Nkrumah', 'kwame.n@example.com', 'ghanaStrong789');


-- Registrations Table
CREATE TABLE registrations (
    registration_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    course_id NUMBER,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (course_id) REFERENCES courses(course_id)
);


CREATE TABLE enrollments (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    course_id INT,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (course_id) REFERENCES courses(course_id)
);

select * from enrollments;

--courses table
CREATE TABLE courses (
  course_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_name VARCHAR2(100),
  course_description VARCHAR2(255)
);

- INSERT courses
INSERT INTO courses (course_name, course_description) 
VALUES ('Computer Science', 'CS course description');

INSERT INTO courses (course_name, course_description) 
VALUES ('Software Engineering', 'SE course description');

INSERT INTO courses (course_name, course_description) 
VALUES ('Cyber Security', 'Cyber course description');


--modules table
CREATE TABLE modules (
  module_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id NUMBER,
  module_code VARCHAR2(20),
  title VARCHAR2(100),
  description VARCHAR2(255),
  FOREIGN KEY (course_id) REFERENCES courses(course_id)
);

  --Computer Science
  INSERT INTO modules (course_id, module_code, title, description)
  VALUES (1, 'COS1903', 'Scala Programming', 'Intro to Scala Programming');

  INSERT INTO modules (course_id, module_code, title, description)
  VALUES (1, 'COS1920', 'Database Management', 'Relational databases and SQL');

  INSERT INTO modules (course_id, module_code, title, description)
  VALUES (1, 'COS2905', 'Object Oriented Programming (Java)', 'OOP with Java');


  --Software Engeneering
  INSERT INTO modules (course_id, module_code, title, description)
  VALUES (2, 'SE3906', 'Interaction Design', 'UX/UI and Interaction principles');

  INSERT INTO modules (course_id, module_code, title, description)
  VALUES (2, 'SE3410', 'Web App Pen Testing', 'Testing web applications for vulnerabilities');

  INSERT INTO modules (course_id, module_code, title, description)
  VALUES (2, 'SE3406', 'Fuzzy Logic', 'Fuzzy logic and knowledge-based systems');

  INSERT INTO modules (course_id, module_code, title, description)
  VALUES (2, 'SE3613', 'Data Mining', 'Data analysis techniques');



--Cyber Security
  INSERT INTO modules (course_id, module_code, title, description)
  VALUES (21, 'SE3901', 'C Programming', 'Fundamentals of C programming');

  INSERT INTO modules (course_id, module_code, title, description)
  VALUES (21, 'SE3902', 'Cyber Security Law', 'Cyber law and security management');

  INSERT INTO modules (course_id, module_code, title, description)
  VALUES  (21, 'SE3903', 'Linux Security', 'Hardening and securing Linux systems');

  INSERT INTO modules (course_id, module_code, title, description)
  VALUES  (21, 'SE3904', 'Cyber Threat Intelligence', 'Incident response and threat hunting');



select * from courses;
select * from modules;
select * from users;